### ISSUE TITLE
Add a way to configure node.js heap size.

### ISSUE THREAD

**Issue by vprus** [gadsme/charts#45]
The Cube's production checklist (https://cube.dev/docs/product/deployment/production-checklist#memory-and-cpu) recommends that refresh worker has 6GB of memory, and also say that NODE_OPTIONS must be adjusted for it to use that memory.

The only way to accomplish that with the current chart is the extraEnvVars variable. However, it also applies to the API pods, so it's not possible to give different memory to API and worker.

It would be great if either:
- there is 'memory' option for both API and workers, which is translated into both K8S resources and into NODE_OPTIONS env var.
- or, there are separate env var setting for API and worker.

**Comment by lvauvillier** [comment]
Hi @vprus, thanks a lot for reporting this.
I'm currently working on a new release, i'll add the env var setting option.

**Comment by lvauvillier** [comment]
Fixed.

Just add this config to your values.yaml file:
```yaml
worker:
  extraEnvVars:
    - name: NODE_OPTIONS
      value: --max-old-space-size=6144
```
